# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEoRc9ej9BUCGRXVp7ih7U3uNRAJ3JUA
"""

import streamlit as st
import pandas as pd
from data_cleaning import clean_data
from eda import plot_correlation_matrix
from regression import perform_regression
from utils import load_data_from_google_sheets

# Sidebar for Google Sheet ID input
st.sidebar.header("Google Sheets Input")
sheet_id = st.sidebar.text_input("Enter your Google Sheet ID:", "")

# Initialize a variable for the cleaned data
df_cleaned = None

# Load data from Google Sheets if a sheet_id is provided
if sheet_id:
    st.sidebar.header("Data Processing")
    
    if st.sidebar.button("Load and Clean Data"):
        # Attempt to clean data
        df_cleaned = clean_data(sheet_id)
        
        if df_cleaned is None or df_cleaned.empty:
            st.error("Failed to load or clean data. Please check the Google Sheet ID and ensure data is valid.")
        else:
            st.write("Cleaned Data:")
            st.write(df_cleaned.head())

            # Sidebar options after data is successfully loaded and cleaned
            st.sidebar.header("Analysis")

            if st.sidebar.button("Plot Correlation Matrix"):
                st.subheader('Correlation Matrix')
                plot_correlation_matrix(df_cleaned)

            if st.sidebar.button("Plot Sales by Account Type"):
                st.subheader('Sales Distribution by Account Type')
                plot_sales_by_account_type(df_cleaned)

            if st.sidebar.button("Plot Sales Trend"):
                st.subheader('Monthly Sales Trend')
                plot_sales_trend(df_cleaned)

            if st.sidebar.button("Run Regression"):
                st.subheader('Regression Analysis')
                model, X_test, y_test = perform_regression(df_cleaned)
                st.write(f"Model Coefficients: {model.coef_}")
                st.write(f"Intercept: {model.intercept_}")
else:
    st.write("Please enter a Google Sheet ID to load and clean data.")
