# -*- coding: utf-8 -*-
"""competitor_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEoRc9ej9BUCGRXVp7ih7U3uNRAJ3JUA
"""

def analyze_competitor_impact(df):
    """
    Analyze the impact of competitor brands on sales over time.
    """
    plt.figure(figsize=(10, 6))
    sns.lineplot(x='month', y='sales', hue='compbrand', data=df)
    plt.title("Sales Trend by Competitor Brands")
    plt.xticks(rotation=45)
    plt.show()

# Perform competitor impact analysis
analyze_competitor_impact(cleaned_df)
