# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEoRc9ej9BUCGRXVp7ih7U3uNRAJ3JUA
"""

import pandas as pd
from eda import plot_correlation_matrix
from regression import perform_regression
from data_cleaning import clean_data
from time_series_analysis import decompose_time_series, forecast_sales
from market_segmentation import perform_market_segmentation
from competitor_analysis import analyze_competitor_impact
from future_budget import reallocate_budget
from utils import load_and_clean_data

# Load and clean data from Google Sheets
sheet_id = '1JCzLJ7TmCOXyj3zjbhhSCIWd-p59jyeWfir11kfQg_0'  # Replace with your Google Sheet ID
df_cleaned = load_and_clean_data(sheet_id, strategy='mean')

# Perform EDA
plot_correlation_matrix(df_cleaned)

# Perform regression
model, X_test, y_test = perform_regression(df_cleaned)

# Time series analysis
decompose_time_series(df_cleaned, 'sales')
forecast_sales(df_cleaned, 'sales')

# Market segmentation
perform_market_segmentation(df_cleaned)

# Competitor impact analysis
analyze_competitor_impact(df_cleaned)

# Budget reallocation based on strategy efficiency
total_future_budget = 30_000_000  # Example future budget
new_budget_allocation = reallocate_budget(df_cleaned, total_future_budget)
print("New Budget Allocation:", new_budget_allocation)
