# -*- coding: utf-8 -*-
"""market_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEoRc9ej9BUCGRXVp7ih7U3uNRAJ3JUA
"""

from sklearn.cluster import KMeans
import seaborn as sns
import matplotlib.pyplot as plt

def perform_market_segmentation(df, n_clusters=3):
    """
    Performs market segmentation using K-Means clustering.

    Args:
    df: DataFrame containing the market data
    n_clusters: Number of clusters for K-Means

    Returns:
    DataFrame with cluster assignments and a scatter plot
    """
    # Selecting relevant features for clustering
    features = df[['strategy1', 'strategy2', 'strategy3', 'sales']]

    # Apply K-Means clustering
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    df['segment'] = kmeans.fit_predict(features)

    # Visualize clusters
    sns.scatterplot(x='strategy1', y='sales', hue='segment', data=df, palette='deep')
    plt.title('Market Segmentation Clusters')
    plt.show()

    return df

    from market_segmentation import perform_market_segmentation

    # Perform market segmentation and add cluster column to DataFrame
    segmented_df = perform_market_segmentation(df)