# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEoRc9ej9BUCGRXVp7ih7U3uNRAJ3JUA
"""

from data_cleaning import clean_data

# Google Sheet ID (make sure this is correct)
sheet_id = '1JCzLJ7TmCOXyj3zjbhhSCIWd-p59jyeWfir11kfQg_0'

# Load and clean data
df_cleaned = clean_data(sheet_id)

# Display the first few rows of the cleaned data
print(df_cleaned.head())