# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEoRc9ej9BUCGRXVp7ih7U3uNRAJ3JUA
"""

import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import streamlit as st


# Load data from Google Sheets using API
def load_data_from_google_sheets(sheet_id):
    """
    Load data from a Google Sheet using its Sheet ID via gspread.

    Args:
    sheet_id: The ID of the Google Sheet

    Returns:
    DataFrame containing the loaded data
    """
    # Define the scope and authorize the credentials
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds = ServiceAccountCredentials.from_json_keyfile_name("credentials/digital-river-319418-9cdcda1df227.json", scope)
    
    client = gspread.authorize(creds)

    # Open the Google Sheet by ID
    sheet = client.open_by_key(sheet_id).sheet1

    # Get all data from the Google Sheet and convert it into a DataFrame
    data = sheet.get_all_records()
    df = pd.DataFrame(data)

    return df

# Handle missing values
def handle_missing_values(df, strategy='mean'):
    """
    Handle missing values in the DataFrame.

    Args:
    df: DataFrame containing the data
    strategy: Strategy to handle missing values ('mean', 'median', 'drop')

    Returns:
    DataFrame with missing values handled
    """
    if strategy == 'mean':
        return df.fillna(df.mean())
    elif strategy == 'median':
        return df.fillna(df.median())
    elif strategy == 'drop':
        return df.dropna()
    else:
        return df  # No handling applied

# Load and clean data
def load_and_clean_data(sheet_id, strategy='mean'):
    """
    Load data from Google Sheets and clean it by handling missing values.

    Args:
    sheet_id: Google Sheet ID to load the data from
    strategy: Strategy to handle missing values ('mean', 'median', 'drop')

    Returns:
    Cleaned DataFrame
    """
    # Load data from Google Sheets
    df = load_data_from_google_sheets(sheet_id)
    
    # Handle missing values
    df_cleaned = handle_missing_values(df, strategy)
    
    return df_cleaned
